name: mess_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: 0.13.5
  provider: ^6.0.1
  email_validator: ^2.0.1
  firebase_auth: 0.16.1
  image_picker: ^0.6.5+3
  firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.13
  flutter_svg: ^1.0.0
  google_sign_in: ^5.2.1
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/chat-box.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
